[project]
name = "learning-ms-agent-framework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent-framework>=1.13.0",
    "agent-framework-a2a>=1.0.0b260709",
    "agent-framework-ag-ui>=1.0.1",
    "agent-framework-devui>=1.0.0b260709",
]

[dependency-groups]
dev = [
    "python-pptx>=1.0.2",
]
